#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from collections import defaultdict, Counter
from pathlib import Path
from typing import Any, Dict, List, Tuple

BLOCKED_ACTIONS = [
    "client_facing_claim",
    "automatic_nomination",
    "implementation_execution",
    "production_activation",
    "automatic_merge",
    "credential_handling",
]

GATE_PRIORITY = {
    "BLOCKED_UNSUPPORTED": ("P0_BLOCKER", 100),
    "HUMAN_REVIEW_REQUIRED": ("P1_REVIEW", 85),
    "ASK_FOR_EVIDENCE": ("P2_EVIDENCE_OR_TASK", 70),
    "TASK_ONLY": ("P2_EVIDENCE_OR_TASK", 65),
    "STRUCTURE_ONLY": ("P3_STRUCTURE", 45),
}

DELTA_WEIGHT = {
    "delta_production": 30,
    "delta_domain": 22,
    "delta_conflict": 20,
    "delta_execution": 16,
    "delta_evidence": 14,
    "delta_missingness": 14,
    "delta_rule": 12,
    "delta_human_review": 12,
    "delta_graph_structure": 8,
    "delta_model_behavior": 6,
    "delta_ambiguity": 6,
}

LABELS_BY_DELTA = {
    "delta_production": ["production-block", "readiness"],
    "delta_domain": ["domain-owner", "human-review"],
    "delta_conflict": ["arbitration", "conflict"],
    "delta_execution": ["test-plan", "execution"],
    "delta_evidence": ["evidence-required"],
    "delta_missingness": ["missing-artifact"],
    "delta_rule": ["rule-map"],
    "delta_human_review": ["human-review"],
    "delta_graph_structure": ["graph-repair"],
    "delta_model_behavior": ["calibration"],
    "delta_ambiguity": ["ambiguity"],
}

def load_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))

def write_json(path: Path, obj: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

def write_md(path: Path, lines: List[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")

def task_key(task: Dict[str, Any]) -> Tuple[str, str, str]:
    return (task["source_delta"], task["artifact_type"], task["recommended_gate"])

def priority_for(delta: str, gate: str, task_count: int) -> Tuple[str, int]:
    level, base = GATE_PRIORITY.get(gate, ("P3_STRUCTURE", 40))
    score = base + DELTA_WEIGHT.get(delta, 5) + min(20, max(0, task_count - 1) * 3)
    if gate == "BLOCKED_UNSUPPORTED":
        level = "P0_BLOCKER"
    elif score >= 95:
        level = "P0_BLOCKER"
    elif score >= 80:
        level = "P1_REVIEW"
    elif score >= 60:
        level = "P2_EVIDENCE_OR_TASK"
    elif score >= 40:
        level = "P3_STRUCTURE"
    else:
        level = "P4_CALIBRATION"
    return level, min(100, score)

def cluster_tasks(tasks: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    grouped: Dict[Tuple[str, str, str], List[Dict[str, Any]]] = defaultdict(list)
    for task in tasks:
        grouped[task_key(task)].append(task)
    clusters = []
    for idx, ((delta, artifact_type, gate), items) in enumerate(sorted(grouped.items()), 1):
        priority, score = priority_for(delta, gate, len(items))
        origins = [i["origin"] for i in items]
        clusters.append({
            "cluster_id": f"CLUSTER-{idx:03d}",
            "source_delta": delta,
            "artifact_type": artifact_type,
            "recommended_gate": gate,
            "priority": priority,
            "priority_score": score,
            "task_count": len(items),
            "task_ids": [i["task_id"] for i in items],
            "origins": origins,
            "reason": items[0]["reason"],
            "closure_state": "READY_FOR_ISSUE" if priority in ["P0_BLOCKER", "P1_REVIEW", "P2_EVIDENCE_OR_TASK"] else "OPEN_CANDIDATE",
        })
    return sorted(clusters, key=lambda c: (-c["priority_score"], c["cluster_id"]))

def make_issue(cluster: Dict[str, Any], index: int) -> Dict[str, Any]:
    labels = ["casulo", "graph-telemetry", cluster["priority"].lower()] + LABELS_BY_DELTA.get(cluster["source_delta"], [])
    title = f"[{cluster['priority']}] {cluster['artifact_type']} required for {cluster['source_delta']}"
    body = (
        f"## Context\n"
        f"Generated by CASULO Graph Task Bridge from graph-builder telemetry.\n\n"
        f"## Cluster\n"
        f"- Cluster: `{cluster['cluster_id']}`\n"
        f"- Source delta: `{cluster['source_delta']}`\n"
        f"- Artifact type: `{cluster['artifact_type']}`\n"
        f"- Recommended gate: `{cluster['recommended_gate']}`\n"
        f"- Task count: `{cluster['task_count']}`\n"
        f"- Origins: `{', '.join(cluster['origins'][:20])}`\n\n"
        f"## Required action\n"
        f"{cluster['reason']}\n\n"
        f"## Acceptance criteria\n"
        f"- Evidence or owner is identified.\n"
        f"- Candidate graph relation is either supported, repaired, routed to review, or kept blocked.\n"
        f"- No production automation is enabled by this issue.\n\n"
        f"## Blocked actions\n"
        f"- client-facing claim\n"
        f"- production activation\n"
        f"- automatic merge\n"
    )
    return {
        "issue_id": f"ISSUE-CANDIDATE-{index:03d}",
        "cluster_id": cluster["cluster_id"],
        "title": title,
        "body": body,
        "priority": cluster["priority"],
        "labels": sorted(set(labels)),
        "status": "READY_FOR_REVIEW_NOT_CREATED",
    }

def md_clusters(clusters: List[Dict[str, Any]]) -> List[str]:
    lines = ["# PROD-281..300 Graph Task Bridge Clusters", ""]
    for c in clusters:
        lines.append(f"## {c['cluster_id']} — {c['priority']}")
        lines.append(f"- Delta: `{c['source_delta']}`")
        lines.append(f"- Artifact: `{c['artifact_type']}`")
        lines.append(f"- Gate: `{c['recommended_gate']}`")
        lines.append(f"- Score: `{c['priority_score']}`")
        lines.append(f"- Task count: `{c['task_count']}`")
        lines.append(f"- Closure state: `{c['closure_state']}`")
        lines.append(f"- Reason: {c['reason']}")
        lines.append("")
    return lines

def md_issues(issues: List[Dict[str, Any]]) -> List[str]:
    lines = ["# PROD-281..300 Issue Candidates", ""]
    for issue in issues:
        lines.append(f"## {issue['issue_id']} — {issue['title']}")
        lines.append(f"- Priority: `{issue['priority']}`")
        lines.append(f"- Labels: `{', '.join(issue['labels'])}`")
        lines.append(f"- Status: `{issue['status']}`")
        lines.append("")
        lines.append(issue["body"])
        lines.append("")
    return lines

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", default=".")
    parser.add_argument("--max-issues", type=int, default=12)
    args = parser.parse_args()
    repo = Path(args.repo)
    out = repo / "outputs"
    tasks_path = out / "prod261_280_missing_artifact_tasks.json"
    graph_path = out / "prod261_280_candidate_graph_telemetry.json"
    if not tasks_path.exists():
        raise SystemExit(f"missing {tasks_path}")
    tasks = load_json(tasks_path).get("tasks", [])
    graph = load_json(graph_path).get("graph", {}) if graph_path.exists() else {}

    clusters = cluster_tasks(tasks)
    issue_candidates = [make_issue(c, idx) for idx, c in enumerate(clusters[: args.max_issues], 1)]

    gate_counts = Counter(c["recommended_gate"] for c in clusters)
    delta_counts = Counter(c["source_delta"] for c in clusters)
    priority_counts = Counter(c["priority"] for c in clusters)

    decision = "READY_FOR_ISSUE_REVIEW_AND_TASK_SELECTION"
    if any(c["priority"] == "P0_BLOCKER" for c in clusters):
        decision = "P0_BLOCKERS_REQUIRE_REVIEW_BEFORE_REAL_CASES"

    report = {
        "status": "PASS",
        "bridge": "casulo.graph_task_bridge.v0.1",
        "source_graph_id": graph.get("graph_id", "UNKNOWN"),
        "source_task_count": len(tasks),
        "cluster_count": len(clusters),
        "issue_candidate_count": len(issue_candidates),
        "priority_counts": dict(priority_counts),
        "gate_counts": dict(gate_counts),
        "delta_counts": dict(delta_counts),
        "decision": decision,
        "interpretation": "Graph-builder task candidates were deduplicated and converted into reviewable backlog/issue candidates. This keeps the system practical and prevents endless recommendation loops.",
        "blocked_actions": BLOCKED_ACTIONS,
    }

    closure_policy = {
        "status": "PASS",
        "policy": "Graph task bridge practical closure policy",
        "rules": [
            "Do not create one issue per raw task.",
            "Group by delta, artifact type and gate.",
            "Promote only P0/P1/P2 clusters to issue candidates.",
            "Keep P3/P4 as candidate backlog unless repeated in real cases.",
            "Never auto-create GitHub issues without human approval.",
            "Production blockers stop the real-case sequence until reviewed.",
        ],
        "blocked_actions": BLOCKED_ACTIONS,
    }

    write_json(out / "prod281_300_task_clusters.json", {"status": "PASS", "clusters": clusters})
    write_md(out / "prod281_300_task_clusters.md", md_clusters(clusters))
    write_json(out / "prod281_300_issue_candidates.json", {"status": "PASS", "issue_candidates": issue_candidates})
    write_md(out / "prod281_300_issue_candidates.md", md_issues(issue_candidates))
    write_json(out / "prod281_300_practical_backlog_report.json", report)
    write_json(out / "prod281_300_task_closure_policy.json", closure_policy)

    md_report = [
        "# PROD-281..300 Graph Task Bridge Practical Backlog Report",
        "",
        f"- Status: `{report['status']}`",
        f"- Source graph: `{report['source_graph_id']}`",
        f"- Source task count: `{report['source_task_count']}`",
        f"- Cluster count: `{report['cluster_count']}`",
        f"- Issue candidates: `{report['issue_candidate_count']}`",
        f"- Decision: `{report['decision']}`",
        "",
        "## Priority Counts",
    ]
    for k, v in report["priority_counts"].items():
        md_report.append(f"- `{k}`: `{v}`")
    md_report += ["", "## Gate Counts"]
    for k, v in report["gate_counts"].items():
        md_report.append(f"- `{k}`: `{v}`")
    md_report += ["", "## Delta Counts"]
    for k, v in report["delta_counts"].items():
        md_report.append(f"- `{k}`: `{v}`")
    md_report += ["", "## Interpretation", report["interpretation"]]
    write_md(out / "prod281_300_practical_backlog_report.md", md_report)

    print(json.dumps({"status": "PASS", "clusters": len(clusters), "issue_candidates": len(issue_candidates), "decision": decision}, indent=2, ensure_ascii=False))
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
